Fix taints; Improves tests

diff --git a/tests/run b/tests/run
--- a/tests/run
+++ b/tests/run
@@ -3,14 +3,22 @@
 set -eu
 export PYTHONPATH=../app
 
+RESET="$(tput sgr0)"
+BOLD="$(tput bold)"
+GREEN="$(tput setaf 2)"
+RED="$(tput setaf 1)"
+
 for i in *.json; do
     echo
-    echo === Testing $i ===
+    echo -e "${BOLD}=== Testing $i ===${RESET}"
     kind=$(echo $i| cut -f1 -d-)
     type=$(echo $i| cut -f2 -d-)
-    if python ../app/main.py $kind $type < $i | python ./check-result.py $i; then
-        echo "Passed"
+    python ../app/main.py $kind $type < $i | python ./check-result.py $i
+
+    if [ "${PIPESTATUS[*]}" == "0 0" ]; then
+        echo -e "${GREEN}Passed"
     else
-        echo "Failed"
+        echo -e "${RED}Failed"
     fi
+    echo -ne "$RESET"
 done
